// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import ProfileCheckerController from "./profile_checker_controller"
application.register("profile-checker", ProfileCheckerController)

import StatusController from "./status_controller"
application.register("status", StatusController)
